spring:
  application:
    name: ms-history
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/db_msraces?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: ${PORT:8200}
rabbitmq:
  queue:
    name: race-result-queue
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
