spring:
  application:
    name: ms-races
server:
  port: ${PORT:8100}
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}