spring:
  application:
    name: ms-cars
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/db_mscars?authSource=admin
server:
  port: ${PORT:8000}
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}