spring:
  application:
    name: ms-cars
  data:
    mongodb:
      uri: mongodb://root:root@mongodb-database:27017/db_mscars?authSource=admin
server:
  port: ${PORT:8000}
springdoc:
  api-docs:
    path: /api-docs
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5